---
  - name: install libselinux-python
    yum: name=libselinux-python state=present

  - name: get fqdn 
    shell: hostname -f
    register: fqdn

  - name: set fqdn in network file
    lineinfile: dest=/etc/sysconfig/network regexp=^HOSTNAME= line=HOSTNAME={{ item }}
    with_items: "{{ fqdn.stdout_lines }}"
    register: done

  - name: set fqdn 
    shell: hostname {{ item }}
    with_items: "{{ fqdn.stdout_lines }}"
    when: done|changed

  - name: re-generate fact
    action: setup
    when: done|changed

  - name: copy hosts
    template: src=hosts.j2 dest=/etc/hosts

  - name: disable selinux 
    shell: setenforce 0
    ignore_errors: true

  - name: switch off selinux permanently
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled
    register: ambari_installed
    ignore_errors: true

  - name: Disable firewall
    command: systemctl disable firewalld
    ignore_errors: true
    
  - name: Stop firewall
    command: systemctl stop firewalld
    ignore_errors: true

  - name: install ntp server
    yum: name=ntp state=present

  - name: switch on ntpd
    service: name=ntpd state=started enabled=on
