- name: Provision EC2 instances
  hosts: localhost
  connection: local
  gather_facts: True 
  user: "{{ remote_user }}"
  tags: provisioning
  roles:
#    - ec2_launch

- name: Initial Linux config and Ambari Agent install
  hosts: hadoop_all
  user: "{{ remote_user }}"
  sudo: yes
  roles:
    - prep
    - ambari-agent

- name: Install Ambari Server
  hosts: m1
  user: "{{ remote_user }}"
  sudo: yes
  roles:
    - ambari-server
    
- hosts: hadoop_all
  name: Gather facts from collectors
  user: "{{ remote_user }}"
  tasks: [ ]
    
- name: Provision Hadoop cluster
  gather_facts: True
  hosts: m1
  user: "{{ remote_user }}"
  sudo: yes
  roles:
    - cluster-reg