---
  - name: remove line
    local_action: 
      lineinfile dest=hosts regexp="compute.amazonaws.com" state=absent
  - name: Launch First Master Instance
    ec2: 
      instance_tags:
        Name: HdpTest3
        Role: M1
      group: "{{ security_group }}" 
      instance_type: "{{ instance_type}}" 
      image: "{{ image }}"
      wait: true 
      region: "{{ region }}" 
      keypair: "{{ keypair }}"
    register: ec2
  - name: Add instance to local host group
    local_action: 
      lineinfile dest=hosts insertafter="m1" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
    with_items: "{{ ec2.instances }}"


  - name: Launch Second Master Instance
    ec2: 
      instance_tags:
        Name: HdpTest3
        Role: M2
      group: "{{ security_group }}" 
      instance_type: "{{ instance_type}}" 
      image: "{{ image }}"
      wait: true 
      region: "{{ region }}" 
      keypair: "{{ keypair }}"
    register: ec2
  - name: Add instance to local host group
    local_action: 
      lineinfile dest=hosts insertafter="m2" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
    with_items: "{{ ec2.instances }}"
    
  - name: Launch Third Master Instance
    ec2: 
      instance_tags:
        Name: HdpTest3
        Role: M3
      group: "{{ security_group }}" 
      instance_type: "{{ instance_type}}" 
      image: "{{ image }}"
      wait: true 
      region: "{{ region }}" 
      keypair: "{{ keypair }}"
    register: ec2
  - name: Add instance to local host group
    local_action: 
      lineinfile dest=hosts insertafter="m3" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
    with_items: "{{ ec2.instances }}"
    
  - name: Launch Worker Instances
    ec2: 
      instance_tags:
        Name: HdpTest3
        Role: DN
      group: "{{ security_group }}" 
      instance_type: "{{ instance_type}}" 
      image: "{{ image }}"
      wait: true 
      count: "{{ dn_count }}"
      region: "{{ region }}" 
      keypair: "{{ keypair }}"
    register: ec2
  - name: Add instance to local host group
    local_action: 
      lineinfile dest=hosts insertafter="dn" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    local_action: 
      wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"
